- name: Install the latest version of 8Knot
  hosts: [ospo]
  tasks:
    - name: Download 8Knot
      ansible.builtin.include_role:
        name: eightknot
        tasks_from: download
    - name: Build the 8Knot container image
      ansible.builtin.include_role:
        name: eightknot
        tasks_from: build
