- name: Load extra variables
  ansible.builtin.include_vars:
    file: secrets.yml

- name: Prepare location for compose files
  ansible.builtin.file:
    path: "{{ compose_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
  become: true

- name: Write compose file using jinja2
  ansible.builtin.template:
      src: templates/compose.yml.j2
      dest: "{{ compose_path }}/compose.yml"

- name: Write environment file using jinja2
  ansible.builtin.template:
      src: templates/.env.j2
      dest: "{{ compose_path }}/.env"

- name: Prepare location for caddy config files
  ansible.builtin.file:
    path: /opt/caddy/
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
  become: true

- name: Write Caddyfile using jinja2 
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /opt/caddy/Caddyfile

- name: Prepare location for postgres and nginx config files
  ansible.builtin.file:
    path: /opt/8knot/config
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
  become: true

- name: Copy postgres.conf
  ansible.builtin.copy:
    src: files/postgres.conf
    dest: /opt/8knot/config/postgres.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /opt/8knot/config/nginx.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Mount Augur DB
  ansible.builtin.include_role:
    name: eightknot
    tasks_from: mount_augur