- name: Ensure git is installed
  apt:
    name: git
    state: present
    update_cache: true
  become: true
- name: Ensure docker is installed
  apt:
    pkg:
      - docker
      - docker.io
      - docker-compose
    state: present
    update_cache: true
  become: true
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection