- name: Stop all services
  community.docker.docker_compose_v2:
    project_src: /opt/compose/8knot/
    state: stopped

- name: Start all services
  community.docker.docker_compose_v2:
    project_src: /opt/compose/8knot/
    pull: missing
    env_files: env.list