- name: Install the latest version of 8Knot
  hosts: [eightknot]
  tasks:
    - name: Configure system for 8Knot
      ansible.builtin.include_role:
        name: eightknot
        tasks_from: environment
